# Generated by Django 4.2.26 on 2025-11-19 21:55

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_photo_1_remove_listing_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=listings.models.listing_image_upload_to),
        ),
    ]
