# Generated by Django 4.2.26 on 2025-11-21 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0009_deal_type_to_tr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimportjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Listing import job', 'verbose_name_plural': 'Listing import jobs'},
        ),
        migrations.RemoveConstraint(
            model_name='listing',
            name='listing_deal_type_valid',
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='cookie_file',
            field=models.FileField(blank=True, upload_to='admin_imports/', verbose_name='Cookie file'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='csv_file',
            field=models.FileField(blank=True, upload_to='admin_imports/', verbose_name='CSV file'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='csv_path_cached',
            field=models.CharField(blank=True, max_length=500, verbose_name='CSV path (cached)'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='debug',
            field=models.BooleanField(default=False, verbose_name='Debug'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='delay',
            field=models.FloatField(default=2.0, verbose_name='Delay (seconds)'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished at'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='headed',
            field=models.BooleanField(default=False, verbose_name='Headed (show browser)'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='images_max',
            field=models.PositiveIntegerField(default=15, verbose_name='Max images'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='log',
            field=models.TextField(blank=True, verbose_name='Log'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='no_images',
            field=models.BooleanField(default=False, verbose_name='No images'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='realtors.realtor', verbose_name='Realtor'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='single_url',
            field=models.URLField(blank=True, verbose_name='Single URL'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='skip_geocode',
            field=models.BooleanField(default=False, verbose_name='Skip geocoding'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='listingimportjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='Status'),
        ),
    ]
